version: '2'

networks:
  locustnw:
    external: true

services:
  web:
    image: marvintang/node-web-app
    networks: 
      - locustnw
    ports:
     - "8080:8080"
    volumes:
      - ./:/mnt/locust
    # command: 
